2022-06-24 17:51:04,672 INFO    MainThread:10691 [wandb_init.py:init():525] backend started and connected
2022-06-24 17:51:04,672 INFO    BackendThr:10691 [internal.py:wandb_internal():93] W&B internal server running at pid: 10691, started at: 2022-06-24 17:51:04.672140
2022-06-24 17:51:04,672 DEBUG   MainThread:10691 [config_util.py:dict_from_config_file():100] no default config file found in config-defaults.yaml
2022-06-24 17:51:04,674 INFO    MainThread:10691 [wandb_init.py:init():596] updated telemetry
2022-06-24 17:51:04,676 INFO    WriterThread:10691 [datastore.py:open_for_write():75] open: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220624_175104-xg3trw6x/run-xg3trw6x.wandb
2022-06-24 17:51:04,678 DEBUG   SenderThread:10691 [sender.py:send():235] send: header
2022-06-24 17:51:04,698 INFO    MainThread:10691 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-24 17:51:04,701 DEBUG   SenderThread:10691 [sender.py:send():235] send: run
2022-06-24 17:51:04,951 INFO    MainThread:10691 [wandb_run.py:_on_init():1924] communicating current version
2022-06-24 17:51:04,952 DEBUG   HandlerThread:10691 [handler.py:handle_request():141] handle_request: check_version
2022-06-24 17:51:04,954 INFO    SenderThread:10691 [dir_watcher.py:__init__():205] watching files in: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220624_175104-xg3trw6x/files
2022-06-24 17:51:04,955 INFO    SenderThread:10691 [sender.py:_start_run_threads():815] run started: xg3trw6x with start time 1656060664
2022-06-24 17:51:04,955 DEBUG   SenderThread:10691 [sender.py:send():235] send: summary
2022-06-24 17:51:04,955 INFO    SenderThread:10691 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2022-06-24 17:51:04,956 DEBUG   SenderThread:10691 [sender.py:send_request():249] send_request: check_version
2022-06-24 17:51:05,027 INFO    MainThread:10691 [wandb_run.py:_on_init():1928] got version response upgrade_message: "wandb version 0.12.19 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-06-24 17:51:05,027 INFO    MainThread:10691 [wandb_init.py:init():662] starting run threads in backend
2022-06-24 17:51:05,028 DEBUG   HandlerThread:10691 [handler.py:handle_request():141] handle_request: run_start
2022-06-24 17:51:05,031 DEBUG   HandlerThread:10691 [meta.py:__init__():35] meta init
2022-06-24 17:51:05,031 DEBUG   HandlerThread:10691 [meta.py:__init__():49] meta init done
2022-06-24 17:51:05,031 DEBUG   HandlerThread:10691 [meta.py:probe():209] probe
2022-06-24 17:51:05,032 DEBUG   HandlerThread:10691 [meta.py:_setup_git():199] setup git
2022-06-24 17:51:05,064 DEBUG   HandlerThread:10691 [meta.py:_setup_git():206] setup git done
2022-06-24 17:51:05,065 DEBUG   HandlerThread:10691 [meta.py:_save_pip():53] save pip
2022-06-24 17:51:05,066 DEBUG   HandlerThread:10691 [meta.py:_save_pip():67] save pip done
2022-06-24 17:51:05,066 DEBUG   HandlerThread:10691 [meta.py:_save_conda():74] save conda
2022-06-24 17:51:05,959 INFO    Thread-10 :10691 [dir_watcher.py:_on_file_created():256] file/dir created: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220624_175104-xg3trw6x/files/requirements.txt
2022-06-24 17:51:05,960 INFO    Thread-10 :10691 [dir_watcher.py:_on_file_created():256] file/dir created: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220624_175104-xg3trw6x/files/conda-environment.yaml
2022-06-24 17:51:05,960 INFO    Thread-10 :10691 [dir_watcher.py:_on_file_created():256] file/dir created: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220624_175104-xg3trw6x/files/wandb-summary.json
2022-06-24 17:51:06,225 WARNING MainThread:10691 [wandb_init.py:init():1020] interrupted
Traceback (most recent call last):
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 673, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 234, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 440, in _communicate_run_start
    result = self._communicate(rec)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/holy_joon/anaconda3/envs/pyml/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2022-06-24 17:51:06,234 INFO    MainThread:10691 [internal.py:handle_exit():80] Internal process exited
2022-06-24 17:51:06,236 WARNING MsgRouterThr:10691 [router.py:message_loop():73] EOFError seen in message_loop
