2022-06-19 14:56:23,271 INFO    BackendThr:20628 [internal.py:wandb_internal():93] W&B internal server running at pid: 20628, started at: 2022-06-19 14:56:23.270756
2022-06-19 14:56:23,271 INFO    MainThread:20628 [wandb_init.py:init():525] backend started and connected
2022-06-19 14:56:23,273 DEBUG   MainThread:20628 [config_util.py:dict_from_config_file():100] no default config file found in config-defaults.yaml
2022-06-19 14:56:23,274 INFO    MainThread:20628 [wandb_init.py:init():596] updated telemetry
2022-06-19 14:56:23,275 INFO    WriterThread:20628 [datastore.py:open_for_write():75] open: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/run-31qsumo5.wandb
2022-06-19 14:56:23,278 DEBUG   SenderThread:20628 [sender.py:send():235] send: header
2022-06-19 14:56:23,298 INFO    MainThread:20628 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-19 14:56:23,301 DEBUG   SenderThread:20628 [sender.py:send():235] send: run
2022-06-19 14:56:23,641 INFO    MainThread:20628 [wandb_run.py:_on_init():1924] communicating current version
2022-06-19 14:56:23,643 DEBUG   HandlerThread:20628 [handler.py:handle_request():141] handle_request: check_version
2022-06-19 14:56:23,647 INFO    SenderThread:20628 [dir_watcher.py:__init__():205] watching files in: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/files
2022-06-19 14:56:23,648 INFO    SenderThread:20628 [sender.py:_start_run_threads():815] run started: 31qsumo5 with start time 1655618183
2022-06-19 14:56:23,648 DEBUG   SenderThread:20628 [sender.py:send():235] send: summary
2022-06-19 14:56:23,649 INFO    SenderThread:20628 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2022-06-19 14:56:23,653 DEBUG   SenderThread:20628 [sender.py:send_request():249] send_request: check_version
2022-06-19 14:56:23,704 INFO    MainThread:20628 [internal.py:handle_exit():80] Internal process exited
2022-06-19 14:56:23,706 WARNING MsgRouterThr:20628 [router.py:message_loop():73] EOFError seen in message_loop
